server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/smart_learning_platform"
    username: "root"
    password: "password"
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  signerKey: "d476819e9edca638ffe1b9a9a17d885ab86efdae4359ffe12002fe2f9e72f027"
